# Generated by Django 6.0.3 on 2026-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_nickname',
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=10),
        ),
    ]
